### ISSUE TITLE
nagios-plugin

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#20]
Missing requirements from base distribution:

nothing provides qstat, nothing provides fping, nothing provides perl-Net-SNMP, nothing provides radiusclient-ng-devel

**Comment by ericvh** [comment]
EPEL7 requirement?

**Comment by pawosm-arm** [comment]
is it still broken?

**Comment by ericvh** [comment]
no, you are correct, its been fixed with the correct incorporation of the epel7 libraries.
