### ISSUE TITLE
easybuild: failure to detect cpu frequency fatal

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#23]
[  794s] +++ STAGE 2: installing EasyBuild in /home/abuild/rpmbuild/BUILDROOT/EasyBuild-ohpc-2.5.0-1.1.aarch64/opt/ohpc/pub/libs/easybuild/2.5.0 with EasyBuild from stage 1...
[  794s] 
[  794s] 
[  794s] Traceback (most recent call last):
[  794s]   File "./bootstrap_eb.py", line 658, in <module>
[  794s]     main()
[  794s]   File "./bootstrap_eb.py", line 492, in main
[  794s]     stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
[  794s]   File "./bootstrap_eb.py", line 430, in stage2
[  794s]     easybuild_main()
[  794s]   File "/tmp/tmphTJ2Pq/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.5.0-py2.7.egg/easybuild/main.py", line 163, in main
[  794s]     init_session_state = session_state()
[  794s]   File "/tmp/tmphTJ2Pq/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.5.0-py2.7.egg/easybuild/tools/testing.py", line 139, in session_state
[  794s]     'system_info': get_system_info(),
[  794s]   File "/tmp/tmphTJ2Pq/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.5.0-py2.7.egg/easybuild/tools/systemtools.py", line 470, in get_system_info
[  794s]     'cpu_speed': get_cpu_speed(),
[  794s]   File "/tmp/tmphTJ2Pq/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.5.0-py2.7.egg/easybuild/tools/systemtools.py", line 234, in get_cpu_speed
[  794s]     _log.debug("%s not found to determine max. CPU clock frequency without CPU scaling: %s" % PROC_CPUINFO_FP)
[  794s] TypeError: not enough arguments for format string
[  794s] error: Bad exit status from /var/tmp/rpm-tmp.2sBhfV (%build)
[  794s] 
[  794s] 
[  794s] RPM build errors:
[  794s]     Bad exit status from /var/tmp/rpm-tmp.2sBhfV (%build)

**Comment by pawosm-arm** [comment]
There is more Intel-specifics behind this story. Apart from tests, get_cpu_speed() is also called by atlas.py in _easyblocks_ part like this:
```
        # use cycle accurate timer for timings
        # see http://math-atlas.sourceforge.net/atlas_install/node23.html
        # this should work on Linux with both GCC and Intel compilers
        cpu_freq = int(get_cpu_speed())
        self.cfg.update('configopts', "-D c -DPentiumCPS=%s" % cpu_freq)

```
...where we have _PentiumCPS_ hardcoded.
get_cpu_speed() is written in Python in the _framework_ part where it reads /proc/cpuinfo; unfortunately no CPU speed is provided for AArch64 in /proc/cpuinfo, so it fails:

```
            _log.debug("Trying to determine CPU frequency on Linux via %s" % PROC_CPUINFO_FP)
            cpuinfo_txt = read_file(PROC_CPUINFO_FP)
            # 'cpu MHz' on Linux/x86 (& more), 'clock' on Linux/POWER
            cpu_freq_regex = re.compile(r"^(?:cpu MHz|clock)\s*:\s*(?P<cpu_freq>\d+(?:\.\d+)?)", re.M)
            res = cpu_freq_regex.search(cpuinfo_txt)
            if res:
                cpu_freq = float(res.group('cpu_freq'))
                _log.debug("Found CPU frequency using regex '%s': %s" % (cpu_freq_regex.pattern, cpu_freq))
            else:
                _log.debug("Failed to determine CPU frequency from %s", PROC_CPUINFO_FP)
```

**Comment by pawosm-arm** [comment]
Reading CPU frequency on AArch64 is not staightforward. One possible solution is to parse output from 'perf stat sleep 1' command and get it from 'GHz' line:

> $ perf stat sleep 1
> 
>  Performance counter stats for 'sleep 1':
> 
>           0.604024      task-clock (msec)         #    0.001 CPUs utilized          
>                  1      context-switches          #    0.002 M/sec                  
>                  0      cpu-migrations            #    0.000 K/sec                  
>                 33      page-faults               #    0.055 M/sec                  
>            1198100      cycles                    #    1.984 GHz                    
>    <not supported>      stalled-cycles-frontend  
>    <not supported>      stalled-cycles-backend   
>             505011      instructions              #    0.42  insns per cycle        
>    <not supported>      branches                 
>               9248      branch-misses             #    0.00% of all branches        
> 
>        1.001056070 seconds time elapsed
> 

...but this introduces dependency on _perf_ package

```
$ rpm -q perf
perf-4.4.3-201.fc22.aarch64
```

**Comment by ericvh** [comment]
of course the whole detection of cpu frequency is kind of crap -- this is to create a generic package, who knows what it would be deployed to -- although I suppose since easybuild includes instructions to build libatlas maybe its trying to provide baseclasses to inform auto-tuners?

I know there is some work going on to standardize interfaces a bit better across cpu types, but not sure what the roadmap is.  The other alternative is to incorporate the mhz microbenchmark from lmbench.

Of course, the right answer is probably to have cpufreq installed in kernel and userspace -- that would provide information via sys and if its trying to do autotuning then we need to make sure we are setting governor policy to performance for the tuning process anyways.

Problem is that the softiron systems we are running on don't have cpufreq built for them.

**Comment by ericvh** [comment]
Also should add that there is a whole ongoing through on using /proc/cpuinfo -- the general answer is that it should be avoided.  there are several chains on this in LKML, but here is one: https://patchwork.kernel.org/patch/9162637/

Again - it sort of requires that there be a cpufreq driver installed.

**Comment by pawosm-arm** [comment]
Honestly, none of AArch64 systems here have this cpufreq, so the _perf_ trick still seems useful. Note that it's not the build time that worries me, as easybuild is just a bunch of python scripts that are not compiled (the problem appears at the testing step which can be silenced). What worries me is that end user may somehow cause easybuild to execute its get_cpu_speed() function causing incorrect or sub-optimal outcome.

**Comment by ericvh** [comment]
yeah, I raised that issue with the kernel-devs suggesting either we mandate
cpufreq in the kernel or have a reasonable fallback interface when the full
interface isn't available that cpu-vendors must populate (that may sit on
the same file system points as cpufreq to make things simple).  this has
come up with other packages as well unfortunately.

The problem is that even the intel information could be wrong (because of
cpu thermal throttling, etc.) -- so nothing should really be depending on
it.  Of course, I've never really done a sensitivity test to see what the
relative performance difference is depending on what you tell libatlas
during build.

**Comment by pawosm-arm** [comment]
I don't think it's only libatlas issue, we're seeing it that way because easybuild-easyblocks provide helper for installing it. Easybuild can grow as a local-user build/installation infrastructure (like pip or SPACK) and as more things will be able to be installed using it, somewhere get_cpu_speed() may be used by someone just because it is exported by easybuild API and covered by its tests. So either we introduce patch that removes it from our release of easybuild completely or we work out getfreq routine (e.g. using perf trick) that is usable on most AArch64 systems running currently available kernels by users that not always can mess with the system to install cutting-edge kernel that mabye one day will provide necessary informations in /proc or /sys.

**Comment by ericvh** [comment]
Well, even perf requires kernel modules -- so if we are going to have a
userspace fallback I would suggest sticking with something like mhz.c that
is self-contained.
