### ISSUE TITLE
warewulf-nhc

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#24]
Seems to be: http://warewulf.lbl.gov/trac/changeset/1856

...
common.nhc...ok 60/70
common.nhc...ok 61/70
common.nhc...ok 62/70
common.nhc...ok 63/70
common.nhc...failed 64/70
[  433s] TEST FAILED:  nhc_common_get_max_sys_uid():  $MAX_SYS_UID <- 500:  Got "" but expected "500"
[  433s] make[1]: *** [test] Error 255
[  433s] make[1]: Leaving directory `/home/abuild/rpmbuild/BUILD/warewulf-nhc-1.4.1/test'
[  433s] make: *** [test] Error 2
[  433s] error: Bad exit status from /var/tmp/rpm-tmp.bGyrrS (%check)
[  433s] 
[  433s] 
[  433s] RPM build errors:
[  433s]     Bad exit status from /var/tmp/rpm-tmp.bGyrrS (%check)

**Comment by pawosm-arm** [comment]
nhc_common_get_max_sys_uid() reads this value from /etc/login.defs so I assume /etc is as unavailable as /proc in OBS chroot environment for AArch64 (again, x86_64 chroot is done right and build succeeds). Where can I find chroot environment configuration for AArch64?
