### ISSUE TITLE
petsc-openmpi: build failure with link issue

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#27]
[ 1604s]          CXX arch-linux2-cxx-opt/obj/src/tao/linesearch/interface/dlregis_taolinesearch.o
[ 1605s]          CXX arch-linux2-cxx-opt/obj/src/tao/linesearch/interface/ftn-auto/taolinesearchf.o
[ 1605s]          CXX arch-linux2-cxx-opt/obj/src/tao/linesearch/interface/ftn-custom/ztaolinesearchf.o
[ 1606s]          CXX arch-linux2-cxx-opt/obj/src/tao/leastsquares/impls/pounders/pounders.o
[ 1606s]          CXX arch-linux2-cxx-opt/obj/src/tao/leastsquares/impls/pounders/gqt.o
[ 1609s]      CLINKER /home/abuild/rpmbuild/BUILD/petsc-3.7.0/arch-linux2-cxx-opt/lib/libpetsc.so.3.7.0
[ 1610s] /bin/ld: arch-linux2-cxx-opt/obj/src/sys/info/verboseinfo.o(.text+0x58): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `ompi_mpi_comm_self'
[ 1610s] /bin/ld: final link failed: Nonrepresentable section on output
[ 1610s] collect2: error: ld returned 1 exit status
[ 1610s] gmake[2]: *** [/home/abuild/rpmbuild/BUILD/petsc-3.7.0/arch-linux2-cxx-opt/lib/libpetsc.so.3.7.0] Error 1
[ 1610s] gmake[2]: Leaving directory `/home/abuild/rpmbuild/BUILD/petsc-3.7.0'
[ 1610s] gmake[1]: *** [gnumake] Error 2
[ 1610s] gmake[1]: Leaving directory `/home/abuild/rpmbuild/BUILD/petsc-3.7.0'
[ 1610s] [1;31m**************************ERROR*************************************
[ 1610s]   Error during compile, check arch-linux2-cxx-opt/lib/petsc/conf/make.log
[ 1610s]   Send it and arch-linux2-cxx-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
[ 1610s] ********************************************************************[0;39m[0;49m
[ 1610s] make: *** [all] Error 1
[ 1610s] error: Bad exit status from /var/tmp/rpm-tmp.btfgVe (%build)
[ 1610s] 
[ 1610s] 
[ 1610s] RPM build errors:
[ 1610s]     Bad exit status from /var/tmp/rpm-tmp.btfgVe (%build)

**Comment by pawosm-arm** [comment]
when I was building it myself, I had to set "-fPIC -DPIC" CFLAGS/CXXFLAGS to succesfully avoid this issue.

**Comment by pawosm-arm** [comment]
Yes, setting these flags fixes this issue. It's my first successfully OBS-build package!
```
diff --git a/components/parallel-libs/petsc/SPECS/petsc.spec b/components/parallel-libs/petsc/SPECS/petsc.spec
index 825ab6f..408a272 100644
--- a/components/parallel-libs/petsc/SPECS/petsc.spec
+++ b/components/parallel-libs/petsc/SPECS/petsc.spec
@@ -124,6 +124,9 @@ module load scalapack openblas
         --FFLAGS="-fPIC" \
         --with-blas-lapack-dir=$MKLROOT/lib/intel64 \
 %else
+        --CFLAGS="-fPIC -DPIC" \
+        --CXXFLAGS="-fPIC -DPIC" \
+        --FFLAGS="-fPIC" \
         --with-blas-lapack-lib=$OPENBLAS_LIB/libopenblas.so \
         --with-scalapack-dir=$SCALAPACK_DIR \
 %endif

```
